### ISSUE TITLE
Some thumbnails won't load

### ISSUE THREAD

**Issue by Android-PowerUser** [hardcore-sushi/DroidFS#130]
Despite a high enough file size setting, some thumbnails will not load. It's often different thumbnails that don't load, and sometimes they load and sometimes they don't.

**Comment by hardcore-sushi** [comment]
Yes if you have large files and not enough memory, it will throw an `OutOfMemoryError` exception and won't load the thumbnail. I'm still looking for a better way to display thumbnails, without having to load the entire file into memory.

**Comment by Android-PowerUser** [comment]
Are you sure? This also happens with small files.

Hardcore Sushi ***@***.***> schrieb am Sa., 7. Mai 2022,
12:32:

**Comment by hardcore-sushi** [comment]
I only have this bug with large files. What do you mean by "_small_" files?
It may also be due to the format of your files that Glide cannot get a thumbnail for.

**Comment by Android-PowerUser** [comment]
For example 2MB. The thumbnails sometimes load and sometimes don't, at the
same file.

Hardcore Sushi ***@***.***> schrieb am Sa., 7. Mai 2022,
15:09:

**Comment by hardcore-sushi** [comment]
OK that's strange. Do you get any warnings or errors in logcat?

**Comment by Android-PowerUser** [comment]
I only see that.

--------- beginning of crash
--------- beginning of system
--------- beginning of main


Hardcore Sushi ***@***.***> schrieb am Sa., 7. Mai 2022,
15:12:

**Comment by iff7378** [comment]
I would recommend a warning be displayed when changing the max thumbnail file size. I was unaware that trying to load a thumbnail for large files would cause the app to become no responsive.

**Comment by hardcore-sushi** [comment]
I belive this is related to #219 and should be fixed in v2.1.0.

**Comment by Android-PowerUser** [comment]
@hardcore-sushi I noticed that if I mark all files and release them again, missing thumbnails are loaded. Sometimes I have to do this several times, but it works. Maybe this information will be of use to you.

**Comment by msantana-dev** [comment]
Same issue here

**Comment by hardcore-sushi** [comment]
It should have been fixed by switching to coil. Can you try building the app from source from the latest commit?

**Comment by hardcore-sushi** [comment]
v2.3.0 released with the switch to Coil. Can you still reproduce the bug with it?

**Comment by Android-PowerUser** [comment]
It seems thumbnails aren't being stored in a cache in the volume, which is why it still takes much longer than with a regular file manager. I'll check more closely later to see if the errors are gone.

**Comment by Android-PowerUser** [comment]
I can't add new GocryptFS volumes in version 2.3. This is probably a new issue. I had to create it in a hidden volume

**Comment by hardcore-sushi** [comment]
What do you mean? Can you share any logcat or error messages you encountered?

**Comment by Android-PowerUser** [comment]
I don't seem to have access to the storage. When I open the AOSP file manager via DroidFS, I only see the access options through apps, not through Android itself. It also seems to be a problem with MiXplorer. I couldn't save the logcat either, but I also get the "Downloads" option, so it worked there. The "Select file" option is also available, but the save button doesn't work anywhere. <img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/2758df0a-c256-4991-a44f-e837ab0a161a" /> 
[DroidFS_2026-08-13_19_27_22.log](https://github.com/user-attachments/files/31039465/DroidFS_2026-08-13_19_27_22.log)

**Comment by hardcore-sushi** [comment]
Thank you. That's weird. DroidFS is only asking the system to let the user pick a directory. The system is then fully responsible for what's shown to you. If you get the same behavior with another app it might be an issue with your system. But you said it did work fine with v2.2.0?
When you say "the save button doesn't work anywhere", do you get any error message?
In the logcat you provided there are 2 errors. The first is related to path resolving process:
```
08-12 20:19:15.769 24801 24801 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=287988957, result=-1, data=Intent { dat=content://com.mixplorer.doc/... flg=0xc3 }} to activity {sushi.hardcore.droidfs/sushi.hardcore.droidfs.add_volume.AddVolumeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6036)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:6075)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:78)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:63)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:133)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:103)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:80)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2773)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:109)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8935)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at sushi.hardcore.droidfs.util.PathUtils.getFullPathFromTreeUri(PathUtils.java:154)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at sushi.hardcore.droidfs.add_volume.SelectPathFragment.onDirectoryPicked(SelectPathFragment.kt:250)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at sushi.hardcore.droidfs.add_volume.SelectPathFragment.pickDirectory$lambda$1(SelectPathFragment.kt:75)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:414)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:371)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:845)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:151)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.Activity.onActivityResult(Activity.java:7571)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.Activity.internalDispatchActivityResult(Activity.java:9470)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:9447)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:6025)
08-12 20:19:15.769 24801 24801 E AndroidRuntime: 	... 14 more
```
It seems you selected a volume provided by `com.mixplorer.doc`, which is why the path can't be resolved. But that's strange because the logcat should include debugging information and they're not there. Did this crash the app?

The second is when saving the logcat:
```
08-13 19:19:37.177 31275  4289 E AndroidRuntime: java.io.FileNotFoundException: Not found > null
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:162)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:737)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1876)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1574)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1548)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at sushi.hardcore.droidfs.LogcatActivity$saveTo$1.invokeSuspend(LogcatActivity.kt:77)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:124)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:820)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
08-13 19:19:37.177 31275  4289 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9e44a50, Dispatchers.IO]
```
It looks like the URI selected is invalid. I don't think the app is doing anything wrong here. Does this also crash the app? What directory did you select to trigger this?

**Comment by Android-PowerUser** [comment]
The behavior is the same for every folder. The app does not crash, not in a way that you would see it, but it might seem that way. The log file is not saved at all in 2.2.0 when I try; it just goes back to the settings after a short pause. 2.2.0 delivers:

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/e45af09e-66b7-48a4-adda-e53050bec826" />

**Comment by hardcore-sushi** [comment]
What do you mean by "but it might seem that way"?

What is the path being displayed after you selected a directory? Do you have this same error message with v2.3.0 too?

It would be nice to try with another app than DroidFS. For example, with [MaterialFiles](https://github.com/zhanghai/MaterialFiles), you can click "Add storage" > "External storage". It should open the same system picker as with DroidFS. If you don't see your phone storage here either, it's definitely not an issue with DroidFS but with your system.

**Comment by Android-PowerUser** [comment]
At the 2.3, no error message appears. The app doesn't close, but it jump strangely, I know it from other apps as if the process were crashed.

The same problem exists in MaterialFiles.

DroidFS asks for permission to manage all files. Then DroidFS can do that right away.

**Comment by hardcore-sushi** [comment]
OK so likely a crash. I'll add a fix.

> DroidFS asks for permission to manage all files. Then DroidFS can do that right away.

Sorry but I'm having a hard time trying to understand you. What can DroidFS do right away?

**Comment by Android-PowerUser** [comment]
DroidFS does not need to ask the AOSP file manager for permission to access a folder. It could access all files itself.

**Comment by hardcore-sushi** [comment]
Ah yes, it's already in the [to-do list](https://github.com/hardcore-sushi/DroidFS/blob/master/TODO.md#ux).

Meanwhile, you can just manually enter the path to the volume if you can't select it interactively.
