### ISSUE TITLE
App crash (2.1.0)

### ISSUE THREAD

**Issue by entropy1453** [hardcore-sushi/DroidFS#237]
After update version 2.0.2 to version 2.1.0 I can't start the application, it immediately closes with an error. I have one volume inside gocryptfs (placed in the application data folder on the SD card, all permissions are granted)
OS: Andoid 8.1

java.lang.RuntimeException: Unable to start activity ComponentInfo{sushi.hardcore.droidfs/sushi.hardcore.droidfs.MainActivity}: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: INSERT INTO Volumes SELECT uuid, name, hidden, type, hash, iv FROM (SELECT name, hidden, type, hash, iv, ROW_NUMBER() OVER () i FROM OLD) NATURAL JOIN (SELECT column1 uuid, ROW_NUMBER() OVER () i FROM (VALUES ('36622a17-a452-465c-9eb7-1f0f869ca5c1')));
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: android.database.sqlite.SQLiteException: near "(": syntax error (code 1): , while compiling: INSERT INTO Volumes SELECT uuid, name, hidden, type, hash, iv FROM (SELECT name, hidden, type, hash, iv, ROW_NUMBER() OVER () i FROM OLD) NATURAL JOIN (SELECT column1 uuid, ROW_NUMBER() OVER () i FROM (VALUES ('36622a17-a452-465c-9eb7-1f0f869ca5c1')));
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:891)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:502)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1754)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1683)
	at sushi.hardcore.droidfs.VolumeDatabase.onUpgrade(SourceFile:392)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:338)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:262)
	at sushi.hardcore.droidfs.VolumeDatabase.getVolumes(SourceFile:1)
	at sushi.hardcore.droidfs.adapters.VolumeAdapter.reloadVolumes(SourceFile:7)
	at sushi.hardcore.droidfs.adapters.VolumeAdapter.<init>(Unknown Source:47)
	at sushi.hardcore.droidfs.MainActivity.onCreate(SourceFile:216)
	at android.app.Activity.performCreate(Activity.java:7088)
	at android.app.Activity.performCreate(Activity.java:7079)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	... 9 more

**Comment by hardcore-sushi** [comment]
Thanks for the bug report. It may be due to the use of SQL features not available on older Android versions. I will release a fix soon.

As a workaround, you can delete the app data if you have no hidden volumes. This should skip the database upgrade process.

**Comment by hardcore-sushi** [comment]
Should be fixed with f1a9c1383c0e8f01d92ac2b823c388d70b4ee63c.

**Comment by entropy1453** [comment]
Unfortunately at startup again crash.
I decided to move my storage and delete the app data, now everything works.
I checked also on another device (Android 6), installed version 2.0.2, created a volume, updated to 2.1.0 - crash, then to 2.1.1 - also crash.
But if you install 2.1.0 and then 2.1.1, the program runs correctly.
Perhaps this information will be useful to someone.

**Comment by hardcore-sushi** [comment]
Can you show the crash log for v2.1.1 please ?

**Comment by entropy1453** [comment]
Ok.
java.lang.RuntimeException: Unable to start activity ComponentInfo{sushi.hardcore.droidfs/sushi.hardcore.droidfs.MainActivity}: android.database.sqlite.SQLiteException: unknown error (code 0): Unable to convert BLOB to long
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2895)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1616)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
Caused by: android.database.sqlite.SQLiteException: unknown error (code 0): Unable to convert BLOB to long
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:511)
	at android.database.CursorWindow.getShort(CursorWindow.java:562)
	at android.database.AbstractWindowedCursor.getShort(AbstractWindowedCursor.java:63)
	at sushi.hardcore.droidfs.VolumeDatabase.extractVolumeData(Unknown Source:36)
	at sushi.hardcore.droidfs.VolumeDatabase.getVolumes(SourceFile:1)
	at sushi.hardcore.droidfs.adapters.VolumeAdapter.reloadVolumes(SourceFile:7)
	at sushi.hardcore.droidfs.adapters.VolumeAdapter.<init>(Unknown Source:47)
	at sushi.hardcore.droidfs.MainActivity.onCreate(SourceFile:216)
	at android.app.Activity.performCreate(Activity.java:7088)
	at android.app.Activity.performCreate(Activity.java:7079)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
	... 9 more

**Comment by hardcore-sushi** [comment]
This one is strange, and I cannot reproduce, even on older Android versions. Did you get this while upgrading from v2.0.2 or from v2.1.0? Can you please describe what was the state of your volumes during the upgrade? (name, hidden or not, cryfs or gocryptfs, fingerprint setup?).

**Comment by hardcore-sushi** [comment]
OK, it should now be fixed with v2.1.2 (I hope).

**Comment by entropy1453** [comment]
Tested it, yes! Problem solved.
