### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by efermi** [hardcore-sushi/DroidFS#26]
Version 1.4.5 from F-Droid.
Device Info:
Android build version: G930W8VLS8CTI1
Android release version: 8.0.0
Android SDK version: 26
Android build ID: R16NW.G930W8VLS8CTI1
Device brand: samsung
Device manufacturer: samsung
Device name: heroltebmc
Device model: SM-G930W8
Device product name: heroltebmc
Device hardware name: samsungexynos8890
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
System language: en-US

```
FATAL EXCEPTION: main
Process: sushi.hardcore.droidfs, PID: 12642
java.lang.RuntimeException: Canvas: trying to draw too large(134468880bytes) bitmap.
	at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
	at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:529)
	at android.widget.ImageView.onDraw(ImageView.java:1367)
	at android.view.View.draw(View.java:20373)
	at android.view.View.updateDisplayListIfDirty(View.java:19318)
	at android.view.View.draw(View.java:20096)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19309)
	at android.view.View.draw(View.java:20096)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19309)
	at android.view.View.draw(View.java:20096)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19309)
	at android.view.View.draw(View.java:20096)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19309)
	at android.view.View.draw(View.java:20096)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.updateDisplayListIfDirty(View.java:19309)
	at android.view.View.draw(View.java:20096)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4421)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4207)
	at android.view.View.draw(View.java:20376)
	at com.android.internal.policy.DecorView.draw(DecorView.java:980)
	at android.view.View.updateDisplayListIfDirty(View.java:19318)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:800)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3496)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3283)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2818)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1780)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7827)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
	at android.view.Choreographer.doFrame(Choreographer.java:658)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by hardcore-sushi** [comment]
Yes 134MB is a bit large for an image 😂. That's very strange, do you get the same error when using release from GitHub ?

**Comment by efermi** [comment]
Yes, it's the same with the release APK.

**Comment by efermi** [comment]
Your mention of the image size have got me thinking, I switched to the FHD resolution and it launches and works properly now. When I switch back to WQHD it keeps crashing.

**Comment by efermi** [comment]
Fixed, thank you!
